import { IImage } from 'src/types/image.model';

export const images: IImage[] = [
  {
    id: 1,
    imageUrl: 'assets/images/1.png',
    title: 'Encompassing Love',
    description: [
      'Painting that transcends its darkness with a depth that speaks to the heart. With every side revealing intricate textures and patterns, it offers viewers a multi-dimensional experience of love. The textured surface invites touch, adding a tactile dimension to the exploration of emotions.',
      'Despite its monochromatic hue, the painting exudes warmth and intimacy, evoking the universal language of love that permeates through the darkness. From every angle, viewers can perceive the layers of affection and connection, symbolizing the complexities and richness of love in all its forms.',
    ],
    dimensions: '130x100',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 2,
    imageUrl: 'assets/images/2.png',
    title: 'Fusion',
    description: [
      'Contemporary twist on the classic still life.Each brushstroke and splash of color captures the essence of the flowers, evoking a sense of energy and movement.beauty of nature through a fresh and unconventional lens.',
    ],
    dimensions: '55x60',
    canvasMaterial: 'Cardboard',
    paintMaterial: 'Oil',
  },
  {
    id: 3,
    imageUrl: 'assets/images/3.png',
    title: 'Little Red',
    description: [
      'In "Little Red," I delve into the realm of abstract expressionism with bold strokes and vivid hues, creating a painting that pulsates with raw emotion and intensity. At its core, this piece is a visual symphony, each brushstroke a note in a larger composition that speaks to the depths of the human experience.',
      'The dominant presence of red in "Little Red" serves as a focal point, commanding attention and evoking a myriad of sensations — passion, desire, and perhaps even a hint of danger. It"s a color that demands to be felt, stirring something primal within the viewer and igniting a visceral response that transcends language.',
      'As one explores "Little Red" more deeply, they may uncover layers of symbolism and meaning woven into the fabric of the painting. It is a reflection of the human condition — a tapestry of joy and sorrow, love and longing, triumph and tragedy.',
    ],
    dimensions: '60x80',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 4,
    imageUrl: 'assets/images/4.png',
    title: 'Untitled',
    description: [
      "Visual narrative of raw feelings and unfiltered expression. Each brushstroke carrying the weight of the artist's inner turmoil and elation. Swirls of paint intertwine, forming a chaotic yet harmonious composition that mirrors the complexity of human emotion.",
    ],
    dimensions: '40x50',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 5,
    imageUrl: 'assets/images/5.png',
    title: 'Bloom: A Tapestry of Life and Femininity',
    description: [
      "At the heart of 'Bloom: A Tapestry of Life and Femininity' lies the enigmatic symbolism of the flower, a universal motif representing growth, beauty, and the cyclical nature of existence. Here, the flower serves as a potent symbol of femininity, with its delicate petals unfurling in a gesture of both vulnerability and strength.",
      "It speaks to the resilience of the feminine spirit, capable of enduring life's trials and tribulations while exuding an innate grace and beauty. It is a painting that celebrates the beauty and resilience of the feminine spirit, while also acknowledging the inherent fragility and impermanence of existence.",
      'It is a tribute to the eternal cycle of life, death, and rebirth, and a poignant reminder of the transformative power of creation and renewal.',
    ],
    dimensions: '100x150',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 6,
    imageUrl: 'assets/images/6.png',
    title: 'S2014',
    description: [
      "Painting that delves into the depths of each individual's personal struggles and mental battles. Cast in shades of gray and black, landscape of chaotic strokes and intricate patterns.Some areas are marked by sharp contrasts and chaotic patterns, mirroring the intensity of inner conflict, while others exude a sense of quiet introspection and acceptance.It is a raw and unfiltered portrayal of the inner battles that define our existence, inviting introspection and empathy from those who dare to confront its depths.",
    ],
    dimensions: '50x60',
    canvasMaterial: 'Cardboard',
    paintMaterial: 'Oil',
  },
  {
    id: 7,
    imageUrl: 'assets/images/7.png',
    title: 'Temporal',
    description: [
      "Time seems to bend and weave around the lives of its inhabitants. The figures within the clock represent the temporal nature of existence, with some embracing joyous moments, while others appear contemplative or burdened by the weight of time's passage.",
      'The old wall serves as a testament to the enduring presence of time, its weathered surface bearing the marks of countless years gone by. Yet, within its cracks and crevices, there is a sense of timelessness, as if the past, present, and future converge in this timeless space.',
      'It is a painting that resonates with feelings of nostalgia, introspection, and wonder, prompting us to reflect on the fleeting moments that make up our lives.',
    ],
    dimensions: '50x60',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 8,
    imageUrl: 'assets/images/8.png',
    title: 'Horizon 1',
    description: [
      'A contemporary abstract painting that captures the essence of hope and optimism with its vivid colors and dynamic brushstrokes. The horizon is depicted as a beacon of possibility, boundless potential of the future.',
    ],
    dimensions: '40x50',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 9,
    imageUrl: 'assets/images/9.png',
    title: 'Horizon 2',
    description: [
      'A contemporary abstract painting that captures the essence of hope and optimism with its vivid colors and dynamic brushstrokes. The horizon is depicted as a beacon of possibility, boundless potential of the future.',
    ],
    dimensions: '40x50',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 10,
    imageUrl: 'assets/images/10.png',
    title: 'Horizon 3',
    description: [
      'A contemporary abstract painting that captures the essence of hope and optimism with its vivid colors and dynamic brushstrokes. The horizon is depicted as a beacon of possibility, boundless potential of the future.',
    ],
    dimensions: '40x50',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 11,
    imageUrl: 'assets/images/11.png',
    title: 'Green Passion : A Harmonious Symphony of Earth and Cosmos',
    description: [
      'In my painting, "Green Passion," I embark on a journey that transcends the boundaries of the earthly realm, delving into the cosmic expanse that surrounds us. Inspired by the interconnectedness of the universe and the profound harmony that exists between the terrestrial and the celestial, this piece is a visual exploration of the infinite depths of existence.',
      'At first glance, "Green Deep" envelops the viewer in a lush, verdant embrace, with layers of rich emerald hues cascading across the canvas like waves of foliage swaying in the gentle breeze. greenery serves as a symbol of life, renewal, and vitality, grounding the composition in the earthly realm and inviting the viewer to connect with the natural world on a visceral level.',
      '"Green Passion" is more than just a painting; it"s a meditation on the interconnectedness of all things, a reminder of our place within the vast web of existence. It invites the viewer to contemplate the mysteries of the universe and to marvel at the beauty and complexity of the natural world that surrounds us.',
    ],
    dimensions: '100x150',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 12,
    imageUrl: 'assets/images/12.png',
    title: 'Vivid',
    description: [
      'Bursts with bold colors and abstract forms in a dynamic still life composition. Vibrant hues across the painting, creating an electrifying display of energy and movement. The arrangement of objects is stylized and abstract, with exaggerated shapes and playful distortions.A bold and expressive lens, transforming the ordinary into a kaleidoscope of vibrant delight.',
    ],
    dimensions: '50x60',
    canvasMaterial: 'Cardboard',
    paintMaterial: 'Oil',
  },
  {
    id: 13,
    imageUrl: 'assets/images/13.png',
    title: 'Simple',
    description: [
      "The contrast between the purity of white and the boldness of red creates a striking visual impact, drawing the viewer's gaze to the heart of the painting. The laundry line, with its neatly hung garments, symbolizes the rhythm of everyday life and the beauty found in the mundane.",
      'Yet, there is a sense of quiet contemplation that pervades the scene, as if time itself has momentarily stood still. The scarlet accents serve as focal points, inviting viewers to linger and explore the intricate details of painting.it is a reflection of the moments of stillness and beauty found in the ordinary life',
    ],
    dimensions: '70x70',
    canvasMaterial: 'Cardboard',
    paintMaterial: 'Oil',
  },
  {
    id: 14,
    imageUrl: 'assets/images/14.png',
    title: 'Harmony',
    description: [
      'Painting that envelops you in a world of tranquility and serenity creating a sense of softness and warmth. The gentle strokes and seamless blending of colors evoke a feeling of peace and balance. As you gaze upon it, you can almost feel the soothing energy radiating from the canvas, washing over you with waves of calmness.',
    ],
    dimensions: '70x100',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 15,
    imageUrl: 'assets/images/15.png',
    title: 'Setenity',
    description: [
      '"Serenity" captures the essence of tranquility with its soft palette that invites the viewer to immerse themselves in its serene embrace.The composition is airy and open, allowing the mind to wander and find solace in the simplicity of the scene.',
      'It is a painting that whispers of quiet moments and peaceful reflections, offering a sanctuary from the chaos of the world.',
    ],
    dimensions: '70x100',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
  {
    id: 16,
    imageUrl: 'assets/images/16.png',
    title: 'Sea In My Mind',
    description: [
      "This painting is not a mere representation of the sea; it's an exploration of the intangible qualities that stir within me as an artist when confronted with the vastness and dynamism of the ocean.",
      'As I applied layers of paint onto the canvas, I allowed my emotions to guide my brush, channeling the ever-changing tides of my inner world onto the surface. The result is a harmonious interplay of color, texture, and movement that echoes the ceaseless ebb and flow of the sea itself.',
      "Each brushstroke is imbued with a spectrum of emotions — from the tranquil serenity of a calm sea to the tempestuous chaos of a raging storm. The colors shift and blend seamlessly, evoking a sense of fluidity and motion that transports the viewer to the very heart of the ocean's depths, it becomes a mirror reflecting the complexity and depth of the human experience. It's a testament to the resilience of the human spirit, and a reminder that, like the sea itself, we are capable of weathering life's storms and emerging stronger and more vibrant than ever before.",
    ],
    dimensions: '100x150',
    canvasMaterial: 'Canvas',
    paintMaterial: 'Oil',
  },
];
